name: network
description: network proxy
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  basic_utils: ^5.6.0
  logger: ^1.4.0
  date_format: ^2.0.7
  file_selector: ^0.9.3
  window_manager: ^0.3.4
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

# The following section is specific to Flutter packages.
flutter:
  uses-material-design: true
  assets:
    - assets/certs/ca.crt
    - assets/certs/ca_private.der
